
export default [
  {
    title: 'Дата начала',
    dataIndex: 'dateBeg',
    key: 'dateBeg',
    fixed: 'left',
    width: 100,
    align: 'center' as 'center',
  },
  {
    title: 'Дата конца',
    dataIndex: 'dateEnd',
    key: 'dateEnd',
    fixed: 'left',
    width: 100,
    align: 'center' as 'center',
  },
  {
    title: 'Период',
    dataIndex: 'period',
    key: 'period',
    width: 80,
    align: 'center' as 'center',
  },
  {
    title: 'Перепад давления нижний, кПа',
    dataIndex: 'presDiffBot',
    key: 'presDiffBot',
    width: 110,
    align: 'center' as 'center',
  },
  {
    title: 'Перепад давления верхний, кПа',
    dataIndex: 'presDiffTop',
    key: 'presDiffBot',
    width: 110,
    align: 'center' as 'center',
  },
  {
    title: 'Перепад давления средний, кПа',
    dataIndex: 'presDiffCom',
    key: 'presDiffCom',
    width: 120,
    align: 'center' as 'center',
  },
  {
    title: 'Давление колошникового газа, кПа',
    dataIndex: 'kolDavlenie',
    key: 'kolDavlenie',
    width: 125,
    align: 'center' as 'center',
  },
  {
    title: 'Выход колошниковой пыли, кг/т',
    dataIndex: 'kolDust',
    key: 'kolDust',
    width: 125,
    align: 'center' as 'center',
  },
  {
    title: 'Расход горячего дутья (по прибору), м3/мин',
    dataIndex: 'hotBlastRashod',
    key: 'hotBlastRashod',
    width: 150,
    align: 'center' as 'center',
  },
  {
    title: 'Давление горячего дутья, кПа',
    dataIndex: 'hotBlastDavlenie',
    key: 'hotBlastDavlenie',
    width: 100,
    align: 'center' as 'center',
  },
  {
    title: 'Температура горячего дутья, °С',
    dataIndex: 'hotBlastTemp',
    key: 'hotBlastTemp',
    width: 110,
    align: 'center' as 'center',
  },
  {
    title: 'Расход ПГ, м3/час',
    dataIndex: 'rashodNg',
    key: 'rashodNg',
    width: 90,
    align: 'center' as 'center',
  },
  {
    title: 'Содержание кислорода в дутье, %',
    dataIndex: 'hotBlastO2',
    key: 'hotBlastO2',
    width: 105,
    align: 'center' as 'center',
  },
  {
    title: 'Уровень шихты от механического уровнемера 1, мм',
    dataIndex: 'msl1Lev',
    key: 'msl1Lev',
    width: 150,
    align: 'center' as 'center',
  },
  {
    title: 'Уровень шихты от механического уровнемера 2, мм',
    dataIndex: 'msl2Lev',
    key: 'msl2Lev',
    width: 150,
    align: 'center' as 'center',
  },
  {
    title: 'Уровень шихты от радарного уровнемера, мм',
    dataIndex: 'rslLev',
    key: 'rslLev',
    width: 140,
    align: 'center' as 'center',
  },
  {
    title: 'Уровень шихты заданный, м',
    dataIndex: 'slLevRef',
    key: 'slLevRef',
    width: 120,
    align: 'center' as 'center',
  },
  {
    title: 'Температура колошникового газа 1, °С',
    dataIndex: 'tempATopGas',
    key: 'tempATopGas',
    width: 130,
    align: 'center' as 'center',
  },
  {
    title: 'Температура колошникового газа 2, °С',
    dataIndex: 'tempBTopGas',
    key: 'tempBTopGas',
    width: 130,
    align: 'center' as 'center',
  },
  {
    title: 'Температура колошникового газа 3, °С',
    dataIndex: 'tempCTopGas',
    key: 'tempCTopGas',
    width: 130,
    align: 'center' as 'center',
  },
  {
    title: 'Температура колошникового газа 4, °С',
    dataIndex: 'tempDTopGas',
    key: 'tempDTopGas',
    width: 130,
    align: 'center' as 'center',
  },
  {
    title: 'Температура периферийных газов 1, °С',
    dataIndex: 'temp1PerGas',
    key: 'temp1PerGas',
    width: 130,
    align: 'center' as 'center',
  },
  {
    title: 'Температура периферийных газов 2, °С',
    dataIndex: 'temp2PerGas',
    key: 'temp2PerGas',
    width: 130,
    align: 'center' as 'center',
  },
  {
    title: 'Температура периферийных газов 3, °С',
    dataIndex: 'temp3PerGas',
    key: 'temp3PerGas',
    width: 130,
    align: 'center' as 'center',
  },
  {
    title: 'Температура периферийных газов 4, °С',
    dataIndex: 'temp4PerGas',
    key: 'temp4PerGas',
    width: 130,
    align: 'center' as 'center',
  },
  {
    title: 'Температура периферийных газов 5, °С',
    dataIndex: 'temp5PerGas',
    key: 'temp5PerGas',
    width: 120,
    align: 'center' as 'center',
  },
  {
    title: 'Температура периферийных газов 6, °С',
    dataIndex: 'temp6PerGas',
    key: 'temp6PerGas',
    width: 130,
    align: 'center' as 'center',
  },
  {
    title: 'Температура периферийных газов 7, °С',
    dataIndex: 'temp7PerGas',
    key: 'temp7PerGas',
    width: 130,
    align: 'center' as 'center',
  },
  {
    title: 'Температура периферийных газов 8, °С',
    dataIndex: 'temp8PerGas',
    key: 'temp8PerGas',
    width: 130,
    align: 'center' as 'center',
  },
  {
    title: 'Температура периферийных газов 9, °С',
    dataIndex: 'temp9PerGas',
    key: 'temp9PerGas',
    width: 130,
    align: 'center' as 'center',
  },
  {
    title: 'Температура периферийных газов 10, °С',
    dataIndex: 'temp10PerGas',
    key: 'temp10PerGas',
    width: 130,
    align: 'center' as 'center',
  },
  {
    title: 'Температура периферийных газов 11, °С',
    dataIndex: 'temp11PerGas',
    key: 'temp11PerGas',
    width: 130,
    align: 'center' as 'center',
  },
  {
    title: 'Температура периферийных газов 12, °С',
    dataIndex: 'temp12PerGas',
    key: 'temp12PerGas',
    width: 130,
    align: 'center' as 'center',
  },
  {
    title: 'Температура периферийных газов 13, °С',
    dataIndex: 'temp13PerGas',
    key: 'temp13PerGas',
    width: 130,
    align: 'center' as 'center',
  },
  {
    title: 'Температура периферийных газов 14, °С',
    dataIndex: 'temp14PerGas',
    key: 'temp14PerGas',
    width: 130,
    align: 'center' as 'center',
  },
  {
    title: 'Температура периферийных газов 15, °С',
    dataIndex: 'temp15PerGas',
    key: 'temp15PerGas',
    width: 130,
    align: 'center' as 'center',
  },
  {
    title: 'Температура периферийных газов 16, °С',
    dataIndex: 'temp16PerGas',
    key: 'temp16PerGas',
    width: 130,
    align: 'center' as 'center',
  },
];